apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-003
  name: web-003
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-003
  template:
    metadata:
      labels:
        app: web-003
    spec:
      containers:
      - image: nginx
        name: nginx

