apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: space 
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["create", "get", "update" ,"delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: space
  name: read-pods
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: alok
  apiGroup: rbac.authorization.k8s.io
