apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  namespace: custom
spec:
  volumes:
  - name: mypod 
    persistentVolumeClaim:
      claimName: pv-claim-log
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: mypod 
      mountPath: /log

