apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-pod
  name: web-pod
spec:
  containers:
  - image: nginx
    name: web-pod

---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: web-pod-svc
  name: web-pod-svc
spec:
  selector:
    run: web-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
