apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypvlog
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pv/log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-log
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: pv-claim-log
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: vol
      mountPath: /log

