apiVersion: v1
kind: Service
metadata:
  labels:
    run: audit-web-app
  name: audit-web-app-service
spec:
  selector:
    run: audit-web-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  type: NodePort

